#!/usr/bin/env sh

find . -name 'Makefile.in' -exec rm -f {} \;
find . -name '.deps' -exec rm -rf {} \;
rm -rf autom4te.cache
rm -f config.h.in
rm -f config.h.in~
rm -rf config
rm -f aclocal.m4
rm -rf m4
rm -f configure
rm -f gray-*.tar.gz
